(defun test29 ()
  (let ((a 0)
        (b 0)
        (c 0)
        (d 0)
        (e 0)
        (x 0))
    (message "五文字を入力してください:")
    (setq x (read-number ""))
    (setq a (/ x 10000))
    (setq b (/ (mod x 10000) 1000))
    (setq c (/ (mod x 1000) 100))
    (setq d (/ (mod x 100) 10))
    (setq e (mod x 10))
    (cond
     ((/= a 0)
      (message "は五桁の数字で、その逆の順序は: %d %d %d %d %d" e d c b a))
     ((/= b 0)
      (message "は四桁の数字で、その逆の順序は:" e d c b))
     ((/= c 0)
      (message "は三桁の数字で、その逆の順序は：" e d c))
     ((/= d 0)
      (message "は二桁の数字で、その逆の順序は：" e d))
     ((/= e 0)
      (message "は１桁の数字で、その逆の順序は：" e)))))

(test29)
