(defun test10 ()
  (let ((i 0)
        (j 0)))
  (princ "\1\1\n")
  (let ((i 1))
    (while (< i 11)
      (let ((j 1))
        (while (<= j i)
          (princ "aa")
          (setq j (1+ j))))
      (princ "\n")
      (setq i (1+ i)))))
(test10)
