(defun test16 ()
  (let ((a 0)
        (b 0)
        (tt 0)
        (r 0)
        (n 0))
    (setq a (read-number "a:"))
    (setq b (read-number "b:"))
    (if (< a b)
        (progn
          (setq tt b)
          (setq b a)
          (setq a tt)))
    (setq r (mod a b))
    (setq n (* a b))
    (while (/= r 0)
      (progn
        (setq a b)
        (setq b r)
        (setq r (mod a b))))
    (message "これら二つの数値の最大公約数は%dで、最小公倍数は%dです\n" b (/ n b))))
(test16)
