(defun test4 ()
  (setq day 0)
  (setq month 0)
  (setq year 0)
  (setq sum 0)
  (setq leap 0)
  (message "\n年、月、日を「年、月、日」の形式で入力してください。（2015,12,10）\n")
  (setq year (read-number "year:"))
  (setq month (read-number "month:"))
  (setq day (read-number "day:"))
  (cond
   ((= month 1)
    (setq sum 0))
   ((= month 2)
    (setq sum 31))
   ((= month 3)
    (setq sum 59))
   ((= month 4)
    (setq sum 90))
   ((= month 5)
    (setq sum 120))
   ((= month 6)
    (setq sum 151))
   ((= month 7)
    (setq sum 181))
   ((= month 8)
    (setq sum 212))
   ((= month 9)
    (setq sum 243))
   ((= month 10)
    (setq sum 273))
   ((= month 11)
    (setq sum 304))
   ((= month 12)
    (setq sum 334))
   (t
    (message "data error")))
  (setq sum (+ sum day))
  (if (or (= 0 (mod year 400))
          (and (= 0 (mod year 4)) (/= 0 (mod year 100))))
      (setq leap 1)
    (setq leap 0))
  (if (and (= leap 1) (> month 2))
      (setq sum (1+ sum)))
  (message "これは年の%d日です。" sum)
  (message "\n"))

(test4)
