(defun test30 ()
  (let ((ge 0)
        (shi 0)
        (qian 0)
        (wan 0)
        (x 0))
    (message "五文字を入力してください:")
    (setq x (read-number "x:"))
    (setq wan (/ x 10000))
    (setq qian (/ (mod x 10000) 1000))
    (setq shi (/ (mod x 100) 10))
    (setq ge (mod x 10))
    (if (and (= ge wan) (= shi qian))
        (message "これは回文数字です")
      (message "これは回文数字ではありません"))))

(test30)
