(defun test23 ()
  (let ((i 0)
        (j 0)
        (k 0))
    (setq i 0)
    (while (<= i 3)
      (progn
        (setq j 0)
        (while (<= j (- 2 i))
          (princ " ")
          (setq j (1+ j)))
        (setq k 0)
        (while (<= k (* 2 i))
          (princ "*")
          (setq k (1+ k)))
        (message ""))
      (setq i (1+ i)))
    (setq i 0)
    (while (<= i 2)
      (progn
        (setq j 0)
        (while (<= j i)
          (princ " ")
          (setq j (1+ j)))
        (setq k 0)
        (while (<= k (- 4 (* 2 i)))
          (princ "*")
          (setq k (1+ k)))
        (message ""))
      (setq i (1+ i)))))

(test23)
